let ws,me,state;const $=x=>document.getElementById(x),esc=s=>s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function connect(){ws=new WebSocket((location.protocol==="https:"?"wss://":"ws://")+location.host);ws.onopen=()=>{$("msg").textContent=""};ws.onclose=()=>{$("msg").textContent="Connection lost. Refresh to reconnect."};ws.onmessage=e=>{let m=JSON.parse(e.data);if(m.type==="error"){$("msg").textContent=m.message;$("wmsg").textContent=m.message}if(m.type==="joined"){me=m.selfId;state=m.state;showWait()}if(m.type==="state"){state=m.state;if(state.started)showGame();else renderWait()}}}
connect();function send(type,x={}){if(ws.readyState===1)ws.send(JSON.stringify({type,...x}))}
$("create").onclick=()=>send("create",{name:$("name").value.trim()||"Player"});$("join").onclick=()=>send("join",{name:$("name").value.trim()||"Player",roomId:$("room").value.trim().toUpperCase()});$("start").onclick=()=>send("start");
function showWait(){$("lobby").classList.add("hidden");$("waiting").classList.remove("hidden");renderWait()}
function renderWait(){$("code").textContent=state.roomId;$("players").innerHTML=state.players.map(p=>`<div class="player"><span class="dot ${p.color}"></span><b>${esc(p.name)}</b>${p.id===me?"<br><small>YOU</small>":""}</div>`).join("");$("start").disabled=state.players.length<2;$("wmsg").textContent=state.players.length<2?"Waiting for another player…":"Ready to start."}
function showGame(){$("waiting").classList.add("hidden");$("lobby").classList.add("hidden");$("game").classList.remove("hidden");$("gcode").textContent=state.roomId;$("gplayers").innerHTML=state.players.map(p=>`<div class="player"><span class="dot ${p.color}"></span><b>${esc(p.name)}</b></div>`).join("");build();update()}
function build(){let b=$("board");b.innerHTML="";for(let r=0;r<15;r++)for(let c=0;c<15;c++){let x=document.createElement("div");x.className="cell";if(r<6&&c<6)x.classList.add("home","red");else if(r<6&&c>8)x.classList.add("home","green");else if(r>8&&c<6)x.classList.add("home","blue");else if(r>8&&c>8)x.classList.add("home","yellow");else if(r>=6&&r<=8&&c>=6&&c<=8)x.classList.add("center");b.appendChild(x)}}
function update(){let p=state.players[state.game.turn%state.players.length];$("turn").textContent=p.color.toUpperCase()+"'S TURN";$("status").textContent=p.id===me?"Your turn. Roll the dice.":"Waiting for "+p.name+"…";$("roll").disabled=p.id!==me}
$("roll").onclick=()=>{if(!$("roll").disabled)send("roll")};
